version: 2.1
jobs:
  build:
    docker:
      - image: docker:20.10.7 # Use the Docker version you prefer
    working_directory: ~/project
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7 # Use the Docker version you prefer
      - run:
          name: Build Docker Image
          command: |
            # Build your Docker image
            docker build -t my-docker-image:latest .


  deploy:
    docker:
      - image: docker:20.10.7 # Use the Docker version you prefer
    working_directory: ~/project
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7 # Use the Docker version you prefer
      - run:
          name: Push Docker Image to Docker Hub
          command: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker push my-docker-username/my-docker-image:latest

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
